export const actionTypes = {
    ADD_TODO: "ADD_TODO",
    TOGGLE_TODO: "TOGGLE_TODO",
    CLEAR_COMPLETED: "CLEAR_COMPLETED",
    SET_DISPLAY_FILTER: "SET_DISPLAY_FILTER",
    SET_TODO_ADDED_MESSAGE: "SET_TODO_ADDED_MESSAGE"
};