export const ACTION_TYPES = {
    ADD_TODO: "ADD_TODO",
    TOGGLE_TODO: "TOGGLE_TODO",
    CLEAR_COMPLETED: "CLEAR_COMPLETED",
    REMOVE_TODO: "REMOVE_TODO",
    SET_FILTER: "SET_FILTER",
    SHOW_NOTIFICATION: "SHOW_NOTIFICATION"
};